Feature/hyunjae kwon #1
hoops-project/backend pull request #2
Opened 2024-04-30 04:55 UTC by Hyunjae-Kwon

### 변경사항
**TO-BE**
 - 회원 가입 기능 구현
	 - 아이디, 이메일, 닉네임 중복 검사
	 - 비밀번호 확인
	 - 이메일 형식 검사
		 - ex. hoops@hoops.com → PASS / hoopsahoops.com → FAIL
	 - 비밀번호 형식 검사
		 - 최소 영어 대소문자 1개 이상, 숫자, 특수문자 포함 8자리~13자리
	 - 가입 완료 시 가입한 이메일로 인증 메일 발송 : 유효 기간 3분
		 - 인증 번호 생성하여 email, 인증 번호 reids 에 저장
	 - 비활성화 계정으로 DB 적재 (emailAuth → False)
 - 인증 이메일 클릭 시 계정 활성화 (emailAuth → True)
	 - redis 에 저장된 키, 값 확인 후 인증 완료되면 redis 에서 삭제

### 테스트
- [x] 테스트 코드
- [x] API 테스트

2024-04-30 07:53 UTC, ramyo564 commented on src/main/java/com/zerobase/hoops/users/controller/UserController.java
회원가입을 할 때 유효성 검사가 각 항목별로
나누어져 있는데 API를 나눈 이유가 따로 있는지 궁금합니다.

2024-04-30 07:53 UTC, ramyo564 commented on src/main/java/com/zerobase/hoops/users/dto/SignUpDto.java
> +    @NotBlank(message = "생년월일을 입력하세요.")
validation 라이브러리를 사용중이니 현재 시점보다 미래 날짜 입력을 방지하는 @Past 같은 걸 사용해도 좋을 것 같습니다.

2024-04-30 07:53 UTC, ramyo564 commented on src/main/java/com/zerobase/hoops/users/dto/SignUpDto.java
> +    @NotBlank(message = "성별을 선택하세요.")
성별 같은 경우 프론트단에서도 해결 가능할 거라고 생각하지만
처음부터 enum으로 받는건 어떨까요?

```java
public enum Gender {
    MALE,
    FEMALE,
    OTHER
}

public class User {
    @NotNull(message = "성별을 선택하세요. 예 MALE, FEMALE, OTHER")
    private Gender gender;
}
```

2024-04-30 08:02 UTC, ramyo564 commented on src/main/java/com/zerobase/hoops/users/controller/UserController.java
회원가입을 할 때 유효성 검사가 각 항목별로
나누어져 있는데 API를 나눈 이유가 따로 있는지 궁금합니다.

2024-04-30 11:10 UTC, Hyunjae-Kwon commented on src/main/java/com/zerobase/hoops/users/dto/SignUpDto.java
> +    @NotBlank(message = "생년월일을 입력하세요.")
생년월일이니까 미래의 시간이 될 수 없겠네요..!
말씀해주신 내용 반영하고 추후 날짜 입력 할 때에도 고려해서 사용하도록 하겠습니다 ㅎㅎ

2024-04-30 11:18 UTC, Hyunjae-Kwon commented on src/main/java/com/zerobase/hoops/users/controller/UserController.java
회원 가입 페이지에서 ID 중복, 이메일 중복, 닉네임 중복 버튼을 각각 눌러서 중복 확인을 하기 때문에 나눴습니다!

2024-04-30 11:21 UTC, leejaeeun59357 commented on src/main/java/com/zerobase/hoops/users/controller/UserController.java
> +@Slf4j
별도의 log를 작성하는 메서드가 없어서 이 어노테이션은 없어도 될 것 같습니다!

2024-04-30 11:21 UTC, leejaeeun59357 commented on src/main/java/com/zerobase/hoops/users/repository/UserRepository.java
> +  UserEntity findById(String id);
Optional은 반복적인 null 체크가 줄어드는 장점이 있습니다!

참고하면 좋을 자료 첨부하겠습니다!
https://ccomccomhan.tistory.com/145

2024-04-30 11:22 UTC, ramyo564 commented on src/main/java/com/zerobase/hoops/users/dto/SignUpDto.java
> +    @NotBlank(message = "성별을 선택하세요.")
```java
  @Enumerated(EnumType.STRING)
  private AccountStatus accountStatus;
```

2024-04-30 11:26 UTC, pobiq commented on src/main/java/com/zerobase/hoops/users/dto/SignUpDto.java
> +          .roles(userRoles)
.roles(List.of("ROLE_USER")) 도 좋아보임

2024-04-30 16:06 UTC, ramyo564 commented on src/main/java/com/zerobase/hoops/users/dto/SignUpDto.java
> +    @NotBlank(message = "생년월일을 입력하세요.")
```java
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    @JsonFormat(pattern = "MM/dd/yyyy")
    @Past(message = "미래의 날짜는 불가능 합니다.")
    private LocalDate birthDay;
```
네 맞습니다 그렇다면 이런 식으로 받는건 어떨까요?
String 으로 받는 것 보다는 LocalDate 타입으로 받는 게 유효성이나 데티어 관리 측면에서 더 좋을 것 같습니다!

2024-05-01 00:04 UTC, ramyo564 requested changes

2024-05-01 00:04 UTC, ramyo564 commented on src/main/java/com/zerobase/hoops/users/dto/SignUpDto.java
> +    private String birthday;
```java
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    @JsonFormat(pattern = "MM/dd/yyyy")
    @Past(message = "미래의 날짜는 불가능 합니다.")
    private LocalDate birthDay;
```
네 맞습니다 이전에 말씀해주신 것 처럼 String으로 받을경우 유효성 검사를 사용할 수 없는데요
그렇다면 이런 식 LocalDate 로 받고 `@JsonFormat` 를 활요해서 데이터를 받는건 어떨까요?
String 으로 받는 것 보다는 LocalDate 타입으로 받는 게 유효성이나 데이터 관리 측면에서 더 좋을 것 같습니다!

2024-05-01 00:10 UTC, ramyo564 requested changes

2024-05-01 00:10 UTC, ramyo564 commented on src/main/java/com/zerobase/hoops/entity/UserEntity.java
>    private String birthday;
```java
    private LocalDate birthDay;
```
엔티티에 필드 값을 LocalDate 값으로 받는건 어떨까요? 

```java
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    @JsonFormat(pattern = "MM/dd/yyyy")
    @Past(message = "미래의 날짜는 불가능 합니다.")
    private LocalDate birthDay;
```
그 후 회원가입을 받는 Dto 에서 `@JsonFormat`  활용해서 받는다면 데이터를 처리할 때도 유효성과 일관성을 가져갈 수 있어서 좋다고 생각합니다.

2024-05-01 04:18 UTC, ramyo564 approved these changes
고생하셨습니다!

2024-05-01 07:26 UTC, pobiq approved these changes
고생하셨습니다.

2024-05-01 07:27 UTC, merged